name: 'Trello Custom Field Sync'
description: 'Syncs a custom field when the branch attached to a card is deployed to the branch pushed.'
inputs:
  trello_key:
    description: 'key from Trello (https://trello.com/app-key)'
    required: true
  trello_token:
    description: 'token from Trello (https://trello.com/app-key)'
    required: true
  github_token:
    description: 'token from Github (use secrets.GITHUB_TOKEN)'
    required: true
  trello_board_id:
    description: 'Id of the board to sync with. Can be found in the URL of the main board: (ex. trello.com/b/{ID}/your-board-name)'
    required: true
  trello_label_id:
    description: 'The id of the label to synchronize. Can be found in the trello board JSON: (ex. trello.com/b/{ID}/your-board-name.json)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
